# Generated by Django 5.1.3 on 2024-11-08 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0002_smartphone_smartwatch_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartwatch',
            name='product_category',
        ),
        migrations.AddField(
            model_name='category',
            name='category_description',
            field=models.CharField(default='jd', max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('product_image', models.ImageField(upload_to='product_images')),
                ('product_original_price', models.IntegerField()),
                ('product_selling_price', models.IntegerField()),
                ('small_description', models.CharField(max_length=400)),
                ('large_description', models.CharField(max_length=800)),
                ('product_stock', models.IntegerField()),
                ('product_available', models.BooleanField(default=True)),
                ('stock', models.IntegerField()),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Smartphone',
        ),
        migrations.DeleteModel(
            name='Smartwatch',
        ),
    ]
