# Generated by Django 5.1.3 on 2024-11-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0004_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default='', upload_to='category_images'),
            preserve_default=False,
        ),
    ]
