# Generated by Django 5.1.3 on 2024-11-16 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0016_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
